name: pr-agent
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write
  
jobs:
  pr_agent:
    if: |
      github.event.issue.pull_request &&
      github.event.sender.type != 'Bot' &&
      (contains(github.event.comment.body, '/run') || contains(github.event.comment.body, '/describe') || contains(github.event.comment.body, '/review') || contains(github.event.comment.body, '/improve'))
    runs-on: ubuntu-latest
    steps:
      - name: Run Multiple Commands
        if: contains(github.event.comment.body, '/run')
        run: |
          gh pr comment ${{ github.event.issue.number }} -b "/improve"
          gh pr comment ${{ github.event.issue.number }} -b "/describe"
          gh pr comment ${{ github.event.issue.number }} -b "/review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PR Agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION.AUTO_DESCRIBE: false
          GITHUB_ACTION.AUTO_REVIEW: false
          GITHUB_ACTION.AUTO_IMPROVE: false
          PR_DESCRIPTION.CUSTOM_LABELS: "[]"
