name: pr-agent

on:
  pull_request:
    types: [opened, reopened, review_requested]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_PR_LABELS: '["WIP"]'
          ENABLE_CUSTOM_LABELS: "false"
          PUBLISH_LABELS: "false"
          PR_REVIEWER.ENABLE_REVIEW_LABELS_EFFORT: "false"
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS:      '日本語で記述してください。'
          PR_REVIEWER.EXTRA_INSTRUCTIONS:         '日本語で記述してください。'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: '日本語で回答してください。'
          PR_REVIEWER.PERSISTENT_COMMENT: "true"
          PR_CODE_SUGGESTIONS.PERSISTENT_COMMENT: "true"
          PR_ADD_DOCS.PERSISTENT_COMMENT: "true"
          PR_REVIEWER.INLINE_CODE_COMMENTS: "true"
          
