name: pr-agent

on:
  pull_request:
      types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    name: Run PR Agent
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: run-pr-agent
          reaction: "true"
          reaction-type: "eyes"
      - name: Run PR Agent
        if: steps.command.outputs.command-name == 'run-pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_PR_LABELS: '["ignore-pr-review"]'
          PR_DESCRIPTION.CUSTOM_LABELS: "[]"
          PR_REVIEWER.ENABLE_REVIEW_LABELS_EFFORT: "false"
          PR_DESCRIPTION.ENABLE_PR_TYPE: "false"
          PR_REVIEWER.PERSISTENT_COMMENT: "true"
          PR_CODE_SUGGESTIONS.PERSISTENT_COMMENT: "true"
          PR_ADD_DOCS.PERSISTENT_COMMENT: "true"
          PR_REVIEWER.INLINE_CODE_COMMENTS: "true"
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "日本語で回答してください。"
