name: pr-agent

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write

env:
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IGNORE_PR_LABELS: '["ignore-pr-review"]'
  PUBLISH_LABELS: "false"
  PR_REVIEWER.PERSISTENT_COMMENT: "true"
  PR_CODE_SUGGESTIONS.PERSISTENT_COMMENT: "true"
  PR_DESCRIPTION.ENABLE_PR_TYPE: "false"
  PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
  PR_REVIEWER.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
  PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "日本語で回答してください。"

jobs:
  pr_describe:
    runs-on: ubuntu-latest
    name: Run PR Describe
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/run-pr-agent') &&
      github.event.sender.type != 'Bot'
    steps:
      - uses: actions/checkout@v4
      - id: pr-describe
        uses: Codium-ai/pr-agent@main
        env:
          PR_AGENT_COMMAND: describe

  pr_review:
    runs-on: ubuntu-latest
    name: Run PR Review
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/run-pr-agent') &&
      github.event.sender.type != 'Bot'
    steps:
      - uses: actions/checkout@v4
      - id: pr-review
        uses: Codium-ai/pr-agent@main
        env:
          PR_AGENT_COMMAND: review

  pr_improve:
    runs-on: ubuntu-latest
    name: Run PR Improve
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/run-pr-agent') &&
      github.event.sender.type != 'Bot'
    steps:
      - uses: actions/checkout@v4
      - id: pr-improve
        uses: Codium-ai/pr-agent@main
        env:
          PR_AGENT_COMMAND: improve
