name: pr-agent

on:
 pull_request_review_comment:
   types: [created]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    name: Run PR Agent
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: run-pr-agent
          reaction: "true"
          reaction-type: "eyes"
      
     - name: Run PR Agent Description
       if: steps.command.outputs.command-name == 'run-pr-agent'
       uses: Codium-ai/pr-agent@main
       with:
         command: describe
       env:
         OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Run PR Agent Review
       if: steps.command.outputs.command-name == 'run-pr-agent'
       uses: Codium-ai/pr-agent@main
       with:
         command: review
       env:
         OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Run PR Agent Improve
       if: steps.command.outputs.command-name == 'run-pr-agent'
       uses: Codium-ai/pr-agent@main
       with:
         command: improve
       env:
         OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
