name: pr-agent

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write

env:
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IGNORE_PR_LABELS: '["ignore-pr-review"]'
  PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
  PR_REVIEWER.EXTRA_INSTRUCTIONS: "日本語で記述してください。"
  PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "日本語で回答してください。"
  PR_COMMANDS: |
    /describe
    /review
    /improve

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/run-pr-agent') &&
      github.event.sender.type != 'Bot'
    steps:
      - uses: actions/checkout@v4
      - uses: Codium-ai/pr-agent@main
